//
//  XMLDefinitions.h
//  iStayHealthy
//
//  Created by peterschmidt on 14/08/2011.
//  Copyright 2011 __MyCompanyName__. All rights reserved.
//

#ifndef iStayHealthy_XMLDefinitions_h
#define iStayHealthy_XMLDefinitions_h

#define XMLPREAMBLE @"<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
//Container element definitions
#define ROOT @"iStayHealthyRecord"
#define RESULTS @"Results"
#define MEDICATIONS @"Medications"
#define MISSEDMEDICATIONS @"MissedMedications"
#define OTHERMEDICATIONS @"OtherMedications"
#define CLINICALCONTACTS @"ClinicalContacts"
#define ILLNESSANDPROCEDURES @"IllnessesAndProcedures"
#define HIVSIDEEFFECTS @"HIVSideEffects"
#define PREVIOUSMEDICATIONS  @"PreviousMedications"
#define WELLNESSES  @"Wellnesses"

//Node Element definitions
#define RESULT @"Result"
#define MEDICATION @"Medication"
#define MISSEDMEDICATION @"MissedMedication"
#define OTHERMEDICATION @"OtherMedication"
#define CONTACTS @"Contacts"
#define SIDEEFFECTS @"SideEffects"
#define PROCEDURES @"Procedures"
#define PREVIOUSMEDICATION @"PreviousMedication"
#define WELLNESS @"Wellness"

//Attributes
#define FROMDEVICE @"fromDevice"
#define FROMDATE @"fromDate"
#define DBVERSION @"dbVersion"
#define MEDICATIONFORM @"MedicationForm"
#define NAME @"Name"
#define IMAGE @"Image"
#define ENDDATE @"EndDate"
#define STARTDATE @"StartDate"
#define DOSE @"Dose"
#define UNIT @"Unit"
#define MISSEDDATE @"MissedDate"
#define DRUG @"Drug"
#define CD4COUNT @"CD4"
#define RESULTSDATE @"ResultsDate"
#define VIRALLOAD @"ViralLoad"
#define CD4PERCENT @"CD4Percent"
#define HEPCVIRALLOAD @"HepCViralLoad"
#define GLUCOSE @"Glucose"
#define TOTALCHOLESTEROL @"TotalCholesterol"
#define LDL @"LDL"
#define HDL @"HDL"
#define TRIGLYCERIDE @"Triglyceride"
#define HEARTRATE @"HeartRate"
#define SYSTOLE @"Systole"
#define DIASTOLE @"Diastole"
#define OXYGENLEVEL @"OxygenLevel"
#define WEIGHT @"Weight"
#define HEMOGLOBULIN @"Hemoglobulin"
#define PLATELET @"PlateletCount"
#define WHITEBLOODCELLS @"WhiteBloodCellCount"
#define REDBLOODCELLS @"redBloodCellCount"
#define CHOLESTEROLRATIO @"cholesterolRatio"
#define CARDIACRISKFACTOR @"cardiacRiskFactor"
#define LIVERALANINETRANSAMINASE @"liverAlanineTransaminase"
#define LIVERASPARTATETRANSAMINASE @"liverAspartateTransaminase"
#define LIVERALKALINEPHOSPHATASE @"liverAlkalinePhosphatase"
#define LIVERALBUMIN @"liverAlbumin"
#define LIVERALANINETOTALBILIRUBIN @"liverAlanineTotalBilirubin"
#define LIVERALANINEDIRECTBILIRUBIN @"liverAlanineDirectBilirubin"
#define LIVERGAMMAGLUTAMYLTRANSPEPTIDASE @"liverGammaGlutamylTranspeptidase"
#define GUID @"UID"
#define CLINICNAME  @"ClinicName"
#define CLINICID @"ClinicID"
#define CLINICSTREET @"ClinicStreet"
#define CLINICPOSTCODE @"ClinicPostcode"
#define CLINICCITY @"ClinicCity"
#define CLINICCONTACTNUMBER @"ClinicContactNumber"
#define RESULTSCONTACTNUMBER @"ResultsContactNumber"
#define CLINICEMAILADDRESS @"ClinicEmailAddress"
#define CLINICWEBSITE @"ClinicWebSite"
#define EMERGENCYCONTACTNUMBER @"EmergencyContactNumber"
#define APPOINTMENTCONTACTNUMBER @"AppointmentContactNumber"
#define SIDEEFFECT @"SideEffect"
#define SIDEEFFECTDATE @"SideEffectDate"
#define ILLNESS @"Illness"
#define DATE @"Date"

#define DOB @"yearOfBirth"
#define ISDIABETIC @"isDiabetic"
#define ISSMOKER @"isSmoker"
#define GENDER @"gender"

#define SLEEPBAROMETER @"sleepBarometer"
#define MOODBAROMETER @"moodBarometer"
#define WELLNESSBAROMETER @"wellnessBarometer"
#define MISSEDREASON @"missedReason"
#define SERIOUSNESS @"seriousness"
#define REASONENDED @"reasonEnded"
#define ISART @"isART"
#define STARTDATE_L @"startDate"
#define ENDDATE_L @"endDate"
#define GUID_L @"uID"

#endif
